### ISSUE TITLE
Support for Matlab 2023b and Apple Silicon

### ISSUE THREAD

**Issue by dkp** [trendscenter/gift#13]
Matlab 2023b has been released with native support for Apple Silicon. 
SPM12 provides Apple Silicon compiled Mex files in their maintenance release here: https://github.com/spm/spm12/tree/maint

I added *mexmaca64​ binaries to the icatb directory in two locations:

- mex files from the main spm directory were renamed with an initial `icatb_​` and added to GroupICAT/icatb/icatb_spm_files​
- mex files from the spm directory `@file_array/private`​ were added to `icatb/icatb_spm_files/@icatb_file_array/private`

GIFT appears to run correctly now on Apple Silicon​

**Comment by sungoku** [comment]
Thank you @dkp, I recompiled the mex files of spm and then followed your instructions, problem solved.

**Comment by dkp** [comment]
Wonderful!  Thank you!
