### ISSUE TITLE
Relationship between GitHub and DockerHub repos

### ISSUE THREAD

**Issue by tsalo** [trendscenter/gift#25]
I'm interested in using the Docker image at https://hub.docker.com/r/trendscenter/gift, but the tags and release schedule don't seem to match up with what's on this repository, plus there's nothing in the documentation linking to the DockerHub repo. I was wondering, is the DockerHub repo associated with the official GIFT package?

**Comment by tsalo** [comment]
I just wanted to follow up. @calhounlab @DrCyPhi do either of you know the answer to this?

**Comment by DrCyPhi** [comment]
Hi! if you want to use GIFT as a Docker image it is located here https://hub.docker.com/u/trends
The latest image is pulled from docker using docker pull trends/gift-bids:v4.0.5.3
More information is found here: https://github.com/trendscenter/gift-bids

**Comment by DrCyPhi** [comment]
Hi!

if you want to use GIFT as a Docker image it is located here https://hub.docker.com/u/trends
The latest image is pulled from docker using docker pull trends/gift-bids:v4.0.5.3
More information is found here: https://github.com/trendscenter/gift-bids
[https://opengraph.githubassets.com/19af809dac4fbc11eb5dbfdba1b3d9ac4652308b985d1a3714543c1b584d07cc/trendscenter/gift-bids]<https://github.com/trendscenter/gift-bids>
GitHub - trendscenter/gift-bids<https://github.com/trendscenter/gift-bids>
Contribute to trendscenter/gift-bids development by creating an account on GitHub.
github.com


Best Regards,
Cyrus
________________________________

**Comment by tsalo** [comment]
Thank you. So to summarize, the Docker image at https://hub.docker.com/r/trendscenter/gift is not being maintained by the GIFT team, and I should stick with the `gift-bids` Docker image. I'll try using that one instead.
